### ISSUE TITLE
Improve search function and other ideas...

### ISSUE THREAD

**Issue by Vandenberg5** [UGS-GIO/rockcore#14]
It would be helpful to be able to search by API without "-", this is what people are used to (you search DOGM's database with the 10 digit API number with no dashes).

It would also be helpful to be able to search by township, range and section.

It would be helpful to be able to select multiple wells using a "box" feature, that then generates a list of the wells selected.  right now you have to click on individual wells to get information.

The initial "well information" table that pops up after you click on a dot should include the "type" (core or cuttings) and depth, as opposed to having to click on a second tab to get this information.

Other items to include in the "well information" table: state, GL (ground elevation), county, box total, top_depth, bottom_depth, formation, core note

**Comment by marshallrobinson** [comment]
Noted.
How does everyone rank these issues in terms of priority, and ease of completing? (Here's my 2-cents)

Difficulty: Would require a completely new search form as the default form only allows one to search data as it appears in the database. You could also or change the data.
> It would be helpful to be able to search by API without "-", this is what people are used to (you search DOGM's database with the 10 digit API number with no dashes).

Difficulty: Fairly simple IF the data is already in the format you want to search by.
> It would also be helpful to be able to search by township, range and section.

Difficulty: This would require @jjhi11 to utilize the drawing tool to query the data and display the results in a jS library (dgrid) table. I think it would take appx 20 hrs...(@jjhi11, what do you think?)
> It would be helpful to be able to select multiple wells using a "box" feature, that then generates a list of the wells selected. right now you have to click on individual wells to get information.

Difficulty: Simple, IF the data is stored in a way that supports this function, and the UI supports this function...we'll keep in touch.
> The initial "well information" table that pops up after you click on a dot should include the "type" (core or cuttings) and depth, as opposed to having to click on a second tab to get this information.

Difficulty: Simple, IF the data is stored in a way that supports this function, and the UI supports this function...we'll keep in touch.
> Other items to include in the "well information" table: state, GL (ground elevation), county, box total, top_depth, bottom_depth, formation, core note

**Comment by Vandenberg5** [comment]
How does everyone rank these issues in terms of priority, and ease of completing? (Here's my 2-cents)

**High - should be easy since there is a column in the inventory with the 10 digit API without dashes**

         Difficulty: Would require a completely new search form as the default form only allows one to search data as it appears in 
         the database. You could also or change the data.

         It would be helpful to be able to search by API without "-", this is what people are used to (you search DOGM's database 
         with the 10 digit API number with no dashes).

**Medium - should also be easy since there are columns in the inventory for T, R, s**

         Difficulty: Fairly simple IF the data is already in the format you want to search by.

          It would also be helpful to be able to search by township, range and section.

**Low - would be nice, but not necessary**

         Difficulty: This would require @jjhi11 to utilize the drawing tool to query the data and display the results in a jS library 
         (dgrid) table. I think it would take appx 20 hrs...(@jjhi11, what do you think?)

         It would be helpful to be able to select multiple wells using a "box" feature, that then generates a list of the wells selected. 
         right now you have to click on individual wells to get information.

**High - again, this info is in inventory**

          Difficulty: Simple, IF the data is stored in a way that supports this function, and the UI supports this function...we'll keep in 
          touch.

          The initial "well information" table that pops up after you click on a dot should include the "type" (core or cuttings) and 
          depth, as opposed to having to click on a second tab to get this information.

**High - should be easy, info is in inventory**

          Difficulty: Simple, IF the data is stored in a way that supports this function, and the UI supports this function...we'll keep in 
          touch.

         Other items to include in the "well information" table: state, GL (ground elevation), county, box total, top_depth, 
         bottom_depth, formation, core note

**Comment by marshallrobinson** [comment]
I will separate these out into their own issues at some point so we can better track progress on them.
