### ISSUE TITLE
Photos for well #54 - blank spaces in thumbnail inventory

### ISSUE THREAD

**Issue by Vandenberg5** [UGS-GIO/rockcore#26]
There are 7 photos that are corrupt and need to be fixed.

![image](https://user-images.githubusercontent.com/69822949/91181290-f99c8c00-e6a5-11ea-959f-0d4a4c792389.png)

**Comment by PNatCoreCenter** [comment]
located the 7 images on the web server.  Identified the same 7 images on local hard drive.  Images available but not able to select or edit or zoom.  The JPG files are corrupted.  Generated new JPG files from the .RAW files.  Uploaded to web server.

**Comment by Vandenberg5** [comment]
it is mostly fixed, but there is still a glitch, one photo has a black bar on the right side, and there is a black space (even though all the photos are there)

![image](https://user-images.githubusercontent.com/69822949/91190869-4e91cf80-e6b1-11ea-85df-06f88ae28b93.png)

**Comment by PNatCoreCenter** [comment]
The black bar is a missing label.  The RAW file has the label in that same spot.  It appears that windows forgot to export that part of the photo.  It appears that we have the complete photo sequence in the directory.  You will need to add Martha to the issue so she can look at the database and see what the blank image is.

**Comment by Vandenberg5** [comment]
The corrupt photos have been fixed, but now there are blank spaces in the photo thumbnail sequence (but all photos are present)

![image](https://user-images.githubusercontent.com/69822949/91195640-67e94a80-e6b6-11ea-9f2e-eabd68241854.png)
