### ISSUE TITLE
Change contact info on main "about" panel for Peter leaving

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/rockcore#34]
**Use the space below (be very specific) to make a suggestion to any of the static text in the application.**
What panel are you suggesting changes for?

right side about panel

Are you suggesting an edit to text that already exists or proposing additional text?

already exists

What do you suggest the text says?

Change the last sentence to "...please contact the UCRC Curator at 801.537.3359." or "...please contact UCRC Office at 801.537.3359."
(Peter Nielsen has left, If we make that sentence more general for contact we won't have to keep changing it when people leave or start. We can also just wait on these changes until a new curator starts and put their information in? I don't have a preference.)
Thoughts? @marshallrobinson 

After you propose new text, the Project Manager (Marshall) will have it reviewed by:
- [ ] Stephanie Carney
- [ ] Marshall Robinson

**Comment by marshallrobinson** [comment]
I like what you proposed. @jjhi11 will you please change it to "please contact the UCRC at 801.537.3359."
