### ISSUE TITLE
UCRC inventory download link

### ISSUE THREAD

**Issue by klcummings** [UGS-GIO/rockcore#37]
### What happened?

The UCRC database download link appears to be broken. 

### What did you expect to happen?

na

### Browser Version

chrome

**Comment by marshallrobinson** [comment]
Thank you for letting us know.

@jjhi11, it looks like the issue is with a non-https link. 
Please update the link to: https://geology.utah.gov/docs/xls/ucrc_cores.xlsx

**Comment by marshallrobinson** [comment]
All done
