### ISSUE TITLE
'About' text in the web app

### ISSUE THREAD

**Issue by klcummings** [UGS-GIO/rockcore#38]
### Where is the text you are suggesting changes for?

About section - last sentence 

### What does the current text say?

"If you have any questions regarding the UCRC’s collection or would like to look at any of the samples, please contact Peter Nielsen, UCRC Curator, 801.537.3359, [peternielsen@utah.gov]."

### What do you propose the new text says?

"If you have any questions regarding the UCRC’s collection or would like to look at any of the samples, please contact the UCRC at 801-537-3359."

Essentially remove Peter's email address from this section. My email address (along with MVB's and Tom's) is available on the UCRC website. 

### Who has reviewed your proposed text so far?

na

**Comment by marshallrobinson** [comment]
All done
