### ISSUE TITLE
I need to add some data to this application

### ISSUE THREAD

**Issue by marthajensen** [UGS-GIO/rockcore#5]
Photos from Taylor/Stephanie need to be added to the application

**Background on this project:**
**April 16 email from Stephanie Mills** - "Andrew and I are trying to make sure we've got loose ends lined up for the end of the FY. One aspect of our data preservation grant was getting photos of minerals and core up on webmaps. We spoke with Jay and this seemed to be a relatively simple process, but we are fairly flat out in our group and have time budgeted for GIO - can we discuss if you have someone available?"

**Jay, Marshall, Stephanie, Andrew and I had a meeting on April 20 to discuss this project**

**Second email from Stephanie Mills _to Taylor Boden_ on April 27** -"I had a chat with GIO the other week about the final steps of getting the Crane photos and core photos on the webmaps.

...For core, the main core we've discussed getting online is the Drum Mountain core. But can you send me a list of the other core you're photographing? If there are any other critical minerals districts we will want to prioritize them. Once we've decided what's going online for critical minerals we'll let GIO know. Martha, I'm really sorry, I got distracted after our meeting - were you going to do the core photos? Or was Will/Jay involved somehow? Sorry about that, just remind me what yall need. This will be the UCRC webmap: https://geology.utah.gov/apps/rockcore/index.html.
" After this email, I let Stephanie know that I would take care of the data upload of the photos once they got me the photos along with a spreadsheet of how they connected to the rockcore database.

**Email from Taylor Boden on May 16** "The Drum Mt core photos are there (_referring to a folder on the U drive_-U:\EMP\Critical Minerals and Crane Collection\Drum Mountain Core) and consist of JPG and NEF files." Taylor provided me the photos, but in order to upload them, I asked Taylor  to connect each rockcore photo to a UWI, top depth, and bottom depth before the photos could be uploaded to the database. Taylor sent Peter Nielson an email on May 21 to figure out how to connect UWI, top depth and bottom depth for each photo.

Peter sent an email on May 21 to Martha that said he would finish the rockcore photo spreadsheet for Drum Mtn and send it to me.

**Comment by marthajensen** [comment]
The new photos have been added to the application https://geology.utah.gov/apps/rockcore/

To see the photos, search for well DM-15-1. The photos are 2.5 GB of data so they take a few minutes to load.  It takes a few minutes for the "Photo" button to appear in the well dialogue box, then it takes another few minutes for the photos to load in the viewer. Once I gain access to the Server where the photos are stored, I would like to try to reduce the size of the photos so that they load faster.  Would it be okay if I play around with the size of the photos a little bit @geowomansteph?

**Comment by marshallrobinson** [comment]
I second that those took too long to load and the size of that collection of photos needs optimized for web. My browser stopped loading the images after 1.7 minutes (leaving behind 10s of images that didn't load)

**Comment by StephMills** [comment]
Agreed, the webmap would be more for people to get an idea of inventory. if they need detail they'll have to come in-person, or we can come up with some other solution for them to view high res images. Thanks yall!

**Comment by marthajensen** [comment]
@StephMills I've replaced the images with a lower resolution image for well DM-15-1. The 'photo' button still takes a waiting time to appear, but once you click on the 'photo' button, all the photos appear at once. I think there are other wells that could benefit from reducing photo size to make the app faster. Is this something that I could do and bill to UPG1?

**Comment by StephMills** [comment]
It's not something that falls within my part of UGP1, but there are several people who have their own work streams. I reckon try MVB, as he usually leads the core work. Mine was specific to critical minerals, hence this particular hole.

**Comment by StephMills** [comment]
I've just had a chance to go through the pics, they look great and I think the interface is working fine. This part of the project is wrapped up from my end, thanks again for the great work!
