### ISSUE TITLE
Add download option

### ISSUE THREAD

**Issue by StephMills** [UGS-GIO/rockcore#9]
Can we add an option for users to download the UCRC inventory from the webmap? Option to download as xlsx or shp would be ideal.

**Comment by marshallrobinson** [comment]
Yes, this is a possibility. I thought it already was, but I could be wrong.

**Comment by marshallrobinson** [comment]
Wait, yeah I see it there in the opening "About" panel under "Related Information". Is that what you meant or was it something else I'm missing.

**Comment by StephMills** [comment]
My bad, I'm sorry - my eyes skipped right past it. Would it be possible to just add the word download, so it reads "Download UCRC Inventory Database", in case other people are idiots like me and just scanning for that keyword?

**Comment by Vandenberg5** [comment]
Yes, this already exists in the form of an Excel file.  The Excel file is supposed to be updated each time Peter adds new data.  I am open to calling it something else to make it more obvious that the link is an excel file of the entire inventory.
